# Generated by Django 5.1.15 on 2026-09-23 20:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_alcance', models.CharField(choices=[('GLOBAL', 'Global'), ('AREA', 'Área'), ('UNIDAD', 'Unidad de negocio')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='core.area')),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='core.unidadnegocio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.rolfuncional')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('area__isnull', True), ('tipo_alcance', 'GLOBAL'), ('unidad_negocio__isnull', True)), models.Q(('area__isnull', False), ('tipo_alcance', 'AREA'), ('unidad_negocio__isnull', True)), models.Q(('area__isnull', True), ('tipo_alcance', 'UNIDAD'), ('unidad_negocio__isnull', False)), _connector='OR'), name='ck_asignacionrol_alcance_coherente'), models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario', 'rol', 'area', 'unidad_negocio'), name='uq_asignacion_activa_area_unidad'), models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'GLOBAL')), fields=('usuario', 'rol'), name='uq_asignacion_global_activa')],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolpermiso', to='core.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolpermiso', to='core.rolfuncional')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rol', 'permiso'), name='uq_rol_permiso')],
            },
        ),
    ]
