# Generated by Django 5.1.15 on 2026-09-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permiso_rolfuncional_asignacionrol_rolpermiso'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignacionrol',
            name='uq_asignacion_activa_area_unidad',
        ),
        migrations.AddConstraint(
            model_name='asignacionrol',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'AREA')), fields=('usuario', 'rol', 'area'), name='uq_asignacion_area_activa'),
        ),
        migrations.AddConstraint(
            model_name='asignacionrol',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'UNIDAD')), fields=('usuario', 'rol', 'unidad_negocio'), name='uq_asignacion_unidad_activa'),
        ),
    ]
