# Generated by Django 5.1.15 on 2026-09-23 20:58

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_remove_asignacionrol_uq_asignacion_activa_area_unidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('modelo', models.CharField(max_length=150)),
                ('objeto_repr', models.CharField(max_length=255)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar')], max_length=10)),
                ('origen', models.CharField(choices=[('USUARIO', 'Usuario'), ('SISTEMA', 'Sistema')], max_length=10)),
                ('datos_anteriores', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_regist_content_3b3fcb_idx'), models.Index(fields=['creado_en'], name='core_regist_creado__5f44e0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('origen', 'USUARIO'), ('usuario__isnull', False)), models.Q(('origen', 'SISTEMA'), ('usuario__isnull', True)), _connector='OR'), name='ck_registroauditoria_origen_coherente')],
            },
        ),
    ]
