# Generated by Django 5.1.15 on 2026-09-23 20:58

from django.db import migrations

CODIGO = "auditoria.consultar"
NOMBRE = "Consultar auditoría"


def sembrar_permiso(apps, schema_editor):
    """Único dato sembrado por 0.4: el permiso funcional que autoriza
    consultar `RegistroAuditoria` (CU-040, RQF-117), primer consumidor real
    de `usuario_tiene_permiso()` (RQF-005, parcial).

    No crea `RolFuncional` ni `AsignacionRol` — a quién se le otorga este
    permiso es una decisión 100% administrable desde el Admin, no de esta
    migración. Idempotente: `get_or_create` no duplica el permiso si la
    migración se corre más de una vez.
    """
    Permiso = apps.get_model("core", "Permiso")
    Permiso.objects.get_or_create(codigo=CODIGO, defaults={"nombre": NOMBRE})


def revertir_permiso(apps, schema_editor):
    Permiso = apps.get_model("core", "Permiso")
    Permiso.objects.filter(codigo=CODIGO).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auditoria"),
    ]

    operations = [
        migrations.RunPython(sembrar_permiso, revertir_permiso),
    ]
