# Generated by Django 5.1.15 on 2026-10-05 20:15

import apps.core.models.sistema
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_permiso_auditoria_consultar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(default='Órbita', max_length=60)),
                ('logo', models.FileField(blank=True, upload_to='sistema/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp')), apps.core.models.sistema.validar_logo])),
            ],
            options={
                'verbose_name': 'configuración del sistema',
                'verbose_name_plural': 'configuración del sistema',
            },
        ),
    ]
