# Generated by Django 5.1.15 on 2026-09-28 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_seed_permiso_auditoria_consultar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=15)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('SISTEMA', 'Sistema')], default='MANUAL', max_length=10)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('permite_subtareas', models.BooleanField(default=False)),
                ('completada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipo_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_responsable', to='core.equipo')),
                ('tarea_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtareas', to='tareas.tarea')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('TOMADA', 'Tomada'), ('ASIGNADA', 'Asignada'), ('REASIGNADA', 'Reasignada'), ('DELEGADA', 'Delegada'), ('INICIADA', 'Iniciada'), ('COMPLETADA', 'Completada')], max_length=15)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tareas.tarea')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DelegacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('motivo', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('delegada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegado_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones', to='tareas.tarea')),
            ],
            options={
                'ordering': ['-desde'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tareas.tarea')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_relacion', models.CharField(choices=[('TAREA', 'Tarea'), ('COMENTARIO', 'Comentario')], max_length=15)),
                ('archivo', models.FileField(upload_to='tareas/adjuntos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=255)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tareas.comentariotarea')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tareas.tarea')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('creada_por__isnull', True), ('origen', 'SISTEMA')), models.Q(('origen', 'SISTEMA'), _negated=True), _connector='OR'), name='ck_tarea_sistema_sin_creador'),
        ),
        migrations.AddConstraint(
            model_name='delegaciontarea',
            constraint=models.CheckConstraint(condition=models.Q(('desde__lt', models.F('hasta'))), name='ck_delegaciontarea_vigencia_valida'),
        ),
        migrations.AddConstraint(
            model_name='adjuntotarea',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comentario__isnull', True), ('tarea__isnull', False), ('tipo_relacion', 'TAREA')), models.Q(('comentario__isnull', False), ('tarea__isnull', True), ('tipo_relacion', 'COMENTARIO')), _connector='OR'), name='ck_adjuntotarea_relacion_coherente'),
        ),
    ]
