# Generated by Django 5.1.15 on 2026-09-24 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_seed_permiso_auditoria_consultar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('alcance_visibilidad', models.CharField(choices=[('PUBLICO_INTERNO', 'Público interno'), ('RESTRINGIDO', 'Restringido')], default='RESTRINGIDO', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='catalogo.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_responsable', models.CharField(choices=[('USUARIO', 'Usuario'), ('EQUIPO', 'Equipo')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_responsable', to='core.equipo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='catalogo.servicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('equipo__isnull', True), ('tipo_responsable', 'USUARIO'), ('usuario__isnull', False)), models.Q(('equipo__isnull', False), ('tipo_responsable', 'EQUIPO'), ('usuario__isnull', True)), _connector='OR'), name='ck_servicioresponsable_tipo_coherente'), models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_responsable', 'USUARIO')), fields=('servicio', 'usuario'), name='uq_responsable_usuario_activo'), models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_responsable', 'EQUIPO')), fields=('servicio', 'equipo'), name='uq_responsable_equipo_activo')],
            },
        ),
        migrations.CreateModel(
            name='ServicioVisibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_alcance', models.CharField(choices=[('USUARIO', 'Usuario'), ('AREA', 'Área'), ('UNIDAD', 'Unidad de negocio')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_visibles', to='core.area')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibilidad', to='catalogo.servicio')),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_visibles', to='core.unidadnegocio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_visibles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('area__isnull', True), ('tipo_alcance', 'USUARIO'), ('unidad_negocio__isnull', True), ('usuario__isnull', False)), models.Q(('area__isnull', False), ('tipo_alcance', 'AREA'), ('unidad_negocio__isnull', True), ('usuario__isnull', True)), models.Q(('area__isnull', True), ('tipo_alcance', 'UNIDAD'), ('unidad_negocio__isnull', False), ('usuario__isnull', True)), _connector='OR'), name='ck_serviciovisibilidad_alcance_coherente'), models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'USUARIO')), fields=('servicio', 'usuario'), name='uq_visibilidad_usuario_activa'), models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'AREA')), fields=('servicio', 'area'), name='uq_visibilidad_area_activa'), models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'UNIDAD')), fields=('servicio', 'unidad_negocio'), name='uq_visibilidad_unidad_activa')],
            },
        ),
    ]
