# Generated by Django 5.1.15 on 2026-09-24 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_seed_permiso_catalogo_administrar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='catalogo.formulario'),
        ),
        migrations.CreateModel(
            name='FormularioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('HISTORICA', 'Histórica')], default='BORRADOR', max_length=10)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='catalogo.formulario')),
            ],
            options={
                'ordering': ['formulario_id', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='version_activa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.formularioversion'),
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('TEXTO_LARGO', 'Texto largo'), ('NUMERO', 'Número'), ('FECHA', 'Fecha'), ('FECHA_HORA', 'Fecha y hora'), ('LISTA', 'Lista'), ('MULTILISTA', 'Multilista'), ('BOOLEANO', 'Booleano'), ('ARCHIVO', 'Archivo'), ('USUARIO', 'Usuario'), ('AREA', 'Área'), ('UNIDAD', 'Unidad de negocio'), ('CORREO', 'Correo electrónico'), ('URL', 'URL')], max_length=20)),
                ('etiqueta', models.CharField(max_length=200)),
                ('ayuda', models.TextField(blank=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='catalogo.formularioversion')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcionCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('valor', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='catalogo.campo')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReglaCondicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('operador', models.CharField(choices=[('IGUAL_A', 'Igual a'), ('DISTINTO_DE', 'Distinto de'), ('CONTIENE', 'Contiene'), ('NO_CONTIENE', 'No contiene'), ('MAYOR_QUE', 'Mayor que'), ('MENOR_QUE', 'Menor que'), ('ESTA_VACIO', 'Está vacío'), ('NO_ESTA_VACIO', 'No está vacío')], max_length=20)),
                ('valor', models.CharField(blank=True, max_length=255)),
                ('efecto', models.CharField(choices=[('MOSTRAR', 'Mostrar'), ('OCULTAR', 'Ocultar'), ('REQUERIR', 'Requerir'), ('NO_REQUERIR', 'No requerir')], max_length=20)),
                ('campo_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_como_objetivo', to='catalogo.campo')),
                ('campo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_como_origen', to='catalogo.campo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='formularioversion',
            constraint=models.UniqueConstraint(fields=('formulario', 'numero'), name='uq_formularioversion_numero'),
        ),
        migrations.AddConstraint(
            model_name='opcioncampo',
            constraint=models.UniqueConstraint(fields=('campo', 'valor'), name='uq_opcioncampo_valor'),
        ),
    ]
