# Generated by Django 5.1.15 on 2026-09-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_seed_permiso_formulario_administrar'),
        ('core', '0005_seed_permiso_auditoria_consultar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioContextoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_alcance', models.CharField(choices=[('AREA', 'Área'), ('UNIDAD', 'Unidad de negocio')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contextos_atencion_servicio', to='core.area')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextos_atencion', to='catalogo.servicio')),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contextos_atencion_servicio', to='core.unidadnegocio')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('area__isnull', False), ('tipo_alcance', 'AREA'), ('unidad_negocio__isnull', True)), models.Q(('area__isnull', True), ('tipo_alcance', 'UNIDAD'), ('unidad_negocio__isnull', False)), _connector='OR'), name='ck_contextoatencion_alcance_coherente'), models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'AREA')), fields=('servicio', 'area'), name='uq_contextoatencion_area_activo'), models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo_alcance', 'UNIDAD')), fields=('servicio', 'unidad_negocio'), name='uq_contextoatencion_unidad_activo')],
            },
        ),
    ]
