# Generated by Django 5.1.15 on 2026-09-24 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0004_seed_permiso_formulario_administrar'),
        ('core', '0005_seed_permiso_auditoria_consultar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('valor_texto', models.TextField(blank=True, default='')),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_json', models.JSONField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='catalogo.campo')),
                ('valor_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.area')),
                ('valor_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unidadnegocio')),
                ('valor_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoRespuestaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='tickets/respuestas/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=255)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('respuesta_campo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='tickets.respuestacampo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RespuestaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('formulario_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_formulario', to='catalogo.formularioversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='respuestacampo',
            name='respuesta_formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_campo', to='tickets.respuestaformulario'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('SERVICIO', 'Servicio'), ('PROCESO', 'Proceso')], default='SERVICIO', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('RADICADO', 'Radicado'), ('EN_ATENCION', 'En atención'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('SISTEMA', 'Sistema')], default='MANUAL', max_length=20)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='respuestaformulario',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_formulario', to='tickets.ticket'),
        ),
        migrations.CreateModel(
            name='TicketServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('formulario_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_servicio', to='catalogo.formularioversion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogo.servicio')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_servicio', to='tickets.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='respuestacampo',
            constraint=models.UniqueConstraint(fields=('respuesta_formulario', 'campo'), name='uq_respuestacampo_campo'),
        ),
    ]
