# Generated by Django 5.1.15 on 2026-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='radicado',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='radicado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
