# Generated by Django 5.1.15 on 2026-09-24 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_permiso_auditoria_consultar'),
        ('tickets', '0002_ticket_radicado_ticket_radicado_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='equipo_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_responsable', to='core.equipo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistorialTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('RADICADO', 'Radicado'), ('TOMADO', 'Tomado'), ('ASIGNADO', 'Asignado'), ('REASIGNADO', 'Reasignado')], max_length=20)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TicketContextoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_alcance', models.CharField(choices=[('AREA', 'Área'), ('UNIDAD', 'Unidad de negocio')], max_length=10)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.area')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextos_atencion', to='tickets.ticket')),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unidadnegocio')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('area__isnull', False), ('tipo_alcance', 'AREA'), ('unidad_negocio__isnull', True)), models.Q(('area__isnull', True), ('tipo_alcance', 'UNIDAD'), ('unidad_negocio__isnull', False)), _connector='OR'), name='ck_ticketcontextoatencion_alcance_coherente'), models.UniqueConstraint(condition=models.Q(('tipo_alcance', 'AREA')), fields=('ticket', 'area'), name='uq_ticketcontexto_area'), models.UniqueConstraint(condition=models.Q(('tipo_alcance', 'UNIDAD')), fields=('ticket', 'unidad_negocio'), name='uq_ticketcontexto_unidad')],
            },
        ),
    ]
