# Generated by Django 5.1.15 on 2026-09-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_seed_permiso_tickets_atender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialticket',
            name='tipo_evento',
            field=models.CharField(choices=[('RADICADO', 'Radicado'), ('TOMADO', 'Tomado'), ('ASIGNADO', 'Asignado'), ('REASIGNADO', 'Reasignado'), ('INFORMACION_SOLICITADA', 'Información solicitada'), ('INFORMACION_RESPONDIDA', 'Información respondida')], max_length=30),
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESPONDIDA', 'Respondida')], default='PENDIENTE', max_length=20)),
                ('solicitada_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_informacion', to='tickets.ticket')),
            ],
            options={
                'ordering': ['solicitada_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaSolicitudInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('respondida_en', models.DateTimeField(auto_now_add=True)),
                ('respondida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='tickets.solicitudinformacion')),
            ],
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_relacion', models.CharField(choices=[('TICKET', 'Ticket'), ('COMENTARIO', 'Comentario'), ('SOLICITUD', 'Solicitud de información'), ('RESPUESTA_SOLICITUD', 'Respuesta a solicitud de información')], max_length=20)),
                ('archivo', models.FileField(upload_to='tickets/adjuntos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=255)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.ticket')),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.comentarioticket')),
                ('respuesta_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.respuestasolicitudinformacion')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.solicitudinformacion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comentario__isnull', True), ('respuesta_solicitud__isnull', True), ('solicitud__isnull', True), ('ticket__isnull', False), ('tipo_relacion', 'TICKET')), models.Q(('comentario__isnull', False), ('respuesta_solicitud__isnull', True), ('solicitud__isnull', True), ('ticket__isnull', True), ('tipo_relacion', 'COMENTARIO')), models.Q(('comentario__isnull', True), ('respuesta_solicitud__isnull', True), ('solicitud__isnull', False), ('ticket__isnull', True), ('tipo_relacion', 'SOLICITUD')), models.Q(('comentario__isnull', True), ('respuesta_solicitud__isnull', False), ('solicitud__isnull', True), ('ticket__isnull', True), ('tipo_relacion', 'RESPUESTA_SOLICITUD')), _connector='OR'), name='ck_adjunto_relacion_coherente')],
            },
        ),
    ]
