# Generated by Django 5.1.15 on 2026-09-24 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_historialticket_tipo_evento_comentarioticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('resuelto_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='adjunto',
            name='ck_adjunto_relacion_coherente',
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='tipo_relacion',
            field=models.CharField(choices=[('TICKET', 'Ticket'), ('COMENTARIO', 'Comentario'), ('SOLICITUD', 'Solicitud de información'), ('RESPUESTA_SOLICITUD', 'Respuesta a solicitud de información'), ('RESOLUCION', 'Resolución')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialticket',
            name='tipo_evento',
            field=models.CharField(choices=[('RADICADO', 'Radicado'), ('TOMADO', 'Tomado'), ('ASIGNADO', 'Asignado'), ('REASIGNADO', 'Reasignado'), ('INFORMACION_SOLICITADA', 'Información solicitada'), ('INFORMACION_RESPONDIDA', 'Información respondida'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado'), ('REABIERTO', 'Reabierto')], max_length=30),
        ),
        migrations.AddField(
            model_name='resolucionticket',
            name='resuelto_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resolucionticket',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.resolucionticket'),
        ),
        migrations.AddConstraint(
            model_name='adjunto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comentario__isnull', True), ('resolucion__isnull', True), ('respuesta_solicitud__isnull', True), ('solicitud__isnull', True), ('ticket__isnull', False), ('tipo_relacion', 'TICKET')), models.Q(('comentario__isnull', False), ('resolucion__isnull', True), ('respuesta_solicitud__isnull', True), ('solicitud__isnull', True), ('ticket__isnull', True), ('tipo_relacion', 'COMENTARIO')), models.Q(('comentario__isnull', True), ('resolucion__isnull', True), ('respuesta_solicitud__isnull', True), ('solicitud__isnull', False), ('ticket__isnull', True), ('tipo_relacion', 'SOLICITUD')), models.Q(('comentario__isnull', True), ('resolucion__isnull', True), ('respuesta_solicitud__isnull', False), ('solicitud__isnull', True), ('ticket__isnull', True), ('tipo_relacion', 'RESPUESTA_SOLICITUD')), models.Q(('comentario__isnull', True), ('resolucion__isnull', False), ('respuesta_solicitud__isnull', True), ('solicitud__isnull', True), ('ticket__isnull', True), ('tipo_relacion', 'RESOLUCION')), _connector='OR'), name='ck_adjunto_relacion_coherente'),
        ),
    ]
