# Generated by Django 5.1.15 on 2026-09-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_resolucionticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolucionticket',
            options={'ordering': ['resuelto_en']},
        ),
        migrations.AlterField(
            model_name='resolucionticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='tickets.ticket'),
        ),
    ]
