# Generated by Django 5.1.15 on 2026-09-25 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('INICIO', 'Inicio'), ('TAREA', 'Tarea'), ('APROBACION', 'Aprobación'), ('GACETA', 'Gaceta'), ('CONDICION', 'Condición'), ('ESPERA', 'Espera'), ('TICKET', 'Ticket'), ('HITO', 'Hito'), ('FIN', 'Fin')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['version_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransicionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('prioridad', models.PositiveIntegerField(default=0)),
                ('variable', models.CharField(blank=True, max_length=150)),
                ('operador', models.CharField(blank=True, choices=[('IGUAL_A', 'Igual a'), ('DISTINTO_DE', 'Distinto de'), ('CONTIENE', 'Contiene'), ('NO_CONTIENE', 'No contiene'), ('MAYOR_QUE', 'Mayor que'), ('MENOR_QUE', 'Menor que'), ('ESTA_VACIO', 'Está vacío'), ('NO_ESTA_VACIO', 'No está vacío')], max_length=20)),
                ('valor', models.CharField(blank=True, max_length=255)),
                ('es_fallback', models.BooleanField(default=False)),
                ('etapa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_entrantes', to='workflows.etapa')),
                ('etapa_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_salientes', to='workflows.etapa')),
            ],
            options={
                'ordering': ['etapa_origen_id', 'prioridad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('HISTORICA', 'Histórica')], default='BORRADOR', max_length=10)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='workflows.workflow')),
            ],
            options={
                'ordering': ['workflow_id', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='version_activa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.workflowversion'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='workflows.workflowversion'),
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'numero'), name='uq_workflowversion_numero'),
        ),
    ]
