# Generated by Django 5.1.15 on 2026-09-28 15:13

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_seed_permisos_workflows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('EN_EJECUCION', 'En ejecución'), ('EN_ESPERA', 'En espera'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='EN_EJECUCION', max_length=15)),
                ('contexto', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='workflows.workflowversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanciaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_EJECUCION', 'En ejecución'), ('EN_ESPERA', 'En espera'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('error', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='workflows.etapa')),
                ('transicion_tomada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.transicionetapa')),
                ('instancia_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones_etapa', to='workflows.instanciaworkflow')),
            ],
            options={
                'ordering': ['instancia_workflow_id', 'orden'],
                'indexes': [models.Index(fields=['instancia_workflow', '-orden'], name='idx_instanciaetapa_ultima')],
                'constraints': [models.UniqueConstraint(fields=('instancia_workflow', 'orden'), name='uq_instanciaetapa_orden')],
            },
        ),
    ]
