# Generated by Django 5.1.15 on 2026-09-28 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_permiso_auditoria_consultar'),
        ('tareas', '0001_initial'),
        ('workflows', '0005_seed_periodic_task_reanudar_esperas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciaetapa',
            name='motivo_espera',
            field=models.CharField(blank=True, choices=[('TEMPORAL', 'Espera temporal'), ('TAREA', 'Tarea')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='TareaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('instancia_etapa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tarea_workflow', to='workflows.instanciaetapa')),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vinculo_workflow', to='tareas.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionEtapaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_responsable', models.CharField(blank=True, choices=[('USUARIO', 'Usuario'), ('EQUIPO', 'Equipo')], max_length=10)),
                ('permite_subtareas', models.BooleanField(default=False)),
                ('equipo_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.equipo')),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_tarea', to='workflows.etapa')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('etapa',), name='uq_configuracionetapatarea_etapa'), models.CheckConstraint(condition=models.Q(models.Q(('equipo_responsable__isnull', True), ('tipo_responsable', ''), ('usuario_responsable__isnull', True)), models.Q(('equipo_responsable__isnull', True), ('tipo_responsable', 'USUARIO'), ('usuario_responsable__isnull', False)), models.Q(('equipo_responsable__isnull', False), ('tipo_responsable', 'EQUIPO'), ('usuario_responsable__isnull', True)), _connector='OR'), name='ck_configuracionetapatarea_tipo_coherente')],
            },
        ),
    ]
