# Generated by Django 5.1.15 on 2026-09-28 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprobaciones', '0001_initial'),
        ('core', '0005_seed_permiso_auditoria_consultar'),
        ('workflows', '0006_instanciaetapa_motivo_espera_tareaworkflow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transicionetapa',
            name='resultado_aprobacion',
            field=models.CharField(blank=True, choices=[('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('DEVUELTA', 'Devuelta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='instanciaetapa',
            name='motivo_espera',
            field=models.CharField(blank=True, choices=[('TEMPORAL', 'Espera temporal'), ('TAREA', 'Tarea'), ('APROBACION', 'Aprobación')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ConfiguracionEtapaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('modo', models.CharField(choices=[('SECUENCIAL', 'Secuencial'), ('PARALELA', 'Paralela')], max_length=10)),
                ('politica', models.CharField(blank=True, choices=[('TODOS', 'Todos deben aprobar'), ('CUALQUIERA', 'Cualquiera aprueba')], max_length=10)),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_aprobacion', to='workflows.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaAprobacionWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('esquema', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vinculo_workflow', to='aprobaciones.esquemaaprobacion')),
                ('instancia_etapa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='esquema_aprobacion', to='workflows.instanciaetapa')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteEtapaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField()),
                ('tipo_aprobador', models.CharField(choices=[('USUARIO', 'Usuario'), ('EQUIPO', 'Equipo')], max_length=10)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='workflows.configuracionetapaaprobacion')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.equipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['configuracion_id', 'orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='configuracionetapaaprobacion',
            constraint=models.UniqueConstraint(fields=('etapa',), name='uq_configuracionetapaaprobacion_etapa'),
        ),
        migrations.AddConstraint(
            model_name='configuracionetapaaprobacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('modo', 'PARALELA'), ('politica__in', ['TODOS', 'CUALQUIERA'])), models.Q(('modo', 'SECUENCIAL'), ('politica', '')), _connector='OR'), name='ck_configuracionetapaaprobacion_politica_coherente'),
        ),
        migrations.AddConstraint(
            model_name='participanteetapaaprobacion',
            constraint=models.UniqueConstraint(fields=('configuracion', 'orden'), name='uq_participanteetapaaprobacion_orden'),
        ),
        migrations.AddConstraint(
            model_name='participanteetapaaprobacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equipo__isnull', True), ('tipo_aprobador', 'USUARIO'), ('usuario__isnull', False)), models.Q(('equipo__isnull', False), ('tipo_aprobador', 'EQUIPO'), ('usuario__isnull', True)), _connector='OR'), name='ck_participanteetapaaprobacion_tipo_coherente'),
        ),
    ]
