# Generated by Django 5.1.15 on 2026-09-28 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_seed_permiso_auditoria_consultar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquemaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('modo', models.CharField(choices=[('SECUENCIAL', 'Secuencial'), ('PARALELA', 'Paralela')], max_length=10)),
                ('politica', models.CharField(blank=True, choices=[('TODOS', 'Todos deben aprobar'), ('CUALQUIERA', 'Cualquiera aprueba')], max_length=10)),
                ('resultado', models.CharField(blank=True, choices=[('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('DEVUELTA', 'Devuelta')], max_length=10, null=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('modo', 'PARALELA'), ('politica__in', ['TODOS', 'CUALQUIERA'])), models.Q(('modo', 'SECUENCIAL'), ('politica', '')), _connector='OR'), name='ck_esquemaaprobacion_politica_coherente')],
            },
        ),
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField()),
                ('tipo_aprobador', models.CharField(choices=[('USUARIO', 'Usuario'), ('EQUIPO', 'Equipo')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('DEVUELTA', 'Devuelta'), ('NO_REQUERIDA', 'No requerida')], default='PENDIENTE', max_length=15)),
                ('observacion', models.TextField(blank=True)),
                ('decidida_en', models.DateTimeField(blank=True, null=True)),
                ('aprobador_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.equipo')),
                ('aprobador_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='aprobaciones.esquemaaprobacion')),
            ],
            options={
                'ordering': ['esquema_id', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ReasignacionAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones', to='aprobaciones.aprobacion')),
                ('aprobador_anterior_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.equipo')),
                ('aprobador_anterior_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('aprobador_nuevo_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.equipo')),
                ('aprobador_nuevo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reasignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='aprobacion',
            constraint=models.UniqueConstraint(fields=('esquema', 'orden'), name='uq_aprobacion_orden'),
        ),
        migrations.AddConstraint(
            model_name='aprobacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aprobador_equipo__isnull', True), ('aprobador_usuario__isnull', False), ('tipo_aprobador', 'USUARIO')), models.Q(('aprobador_equipo__isnull', False), ('aprobador_usuario__isnull', True), ('tipo_aprobador', 'EQUIPO')), _connector='OR'), name='ck_aprobacion_tipo_aprobador_coherente'),
        ),
        migrations.AddConstraint(
            model_name='aprobacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decidida_en__isnull', True), ('decidido_por__isnull', True), ('estado__in', ['PENDIENTE', 'NO_REQUERIDA'])), models.Q(('decidida_en__isnull', False), ('decidido_por__isnull', False), ('estado__in', ['APROBADA', 'RECHAZADA', 'DEVUELTA'])), _connector='OR'), name='ck_aprobacion_decision_coherente'),
        ),
    ]
